# Generated by Django 5.1.6 on 2025-07-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_dispute_admin_decision_dispute_decided_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='completed_by_freelancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='confirmed_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
